# Generated by Django 2.0.2 on 2018-06-14 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0006_auto_20180614_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
