# Generated by Django 2.0.2 on 2018-06-15 15:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0011_auto_20180614_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='metadata',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
