# Generated by Django 2.0.2 on 2018-06-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0013_auto_20180618_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisspecies',
            name='analysis',
        ),
        migrations.DeleteModel(
            name='AnalysisSpecies',
        ),
    ]
