# Generated by Django 2.0.2 on 2018-06-25 15:38

from django.db import migrations, models
import django.db.models.deletion
import linker.models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0014_auto_20180618_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisUpload',
            fields=[
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='linker.Analysis')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('gene_data', models.FileField(upload_to=linker.models.get_upload_folder)),
                ('gene_design', models.FileField(upload_to=linker.models.get_upload_folder)),
                ('protein_data', models.FileField(upload_to=linker.models.get_upload_folder)),
                ('protein_design', models.FileField(upload_to=linker.models.get_upload_folder)),
                ('compound_data', models.FileField(upload_to=linker.models.get_upload_folder)),
                ('compound_design', models.FileField(upload_to=linker.models.get_upload_folder)),
            ],
        ),
    ]
