# Generated by Django 2.0.2 on 2018-06-25 21:25

from django.db import migrations, models
import linker.models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0015_analysisupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisupload',
            name='compound_data',
            field=models.FileField(blank=True, null=True, upload_to=linker.models.get_upload_folder),
        ),
        migrations.AlterField(
            model_name='analysisupload',
            name='compound_design',
            field=models.FileField(blank=True, null=True, upload_to=linker.models.get_upload_folder),
        ),
        migrations.AlterField(
            model_name='analysisupload',
            name='gene_data',
            field=models.FileField(blank=True, null=True, upload_to=linker.models.get_upload_folder),
        ),
        migrations.AlterField(
            model_name='analysisupload',
            name='gene_design',
            field=models.FileField(blank=True, null=True, upload_to=linker.models.get_upload_folder),
        ),
        migrations.AlterField(
            model_name='analysisupload',
            name='protein_data',
            field=models.FileField(blank=True, null=True, upload_to=linker.models.get_upload_folder),
        ),
        migrations.AlterField(
            model_name='analysisupload',
            name='protein_design',
            field=models.FileField(blank=True, null=True, upload_to=linker.models.get_upload_folder),
        ),
    ]
