# Generated by Django 2.0.2 on 2018-06-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0018_auto_20180626_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisuploadspecies',
            name='analysis_upload',
        ),
        migrations.RemoveField(
            model_name='analysisupload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='analysisupload',
            name='name',
        ),
        migrations.DeleteModel(
            name='AnalysisUploadSpecies',
        ),
    ]
