# Generated by Django 2.0.2 on 2018-06-29 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0020_analysis_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.CharField(max_length=100)),
                ('annotation', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('analysis_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.AnalysisData')),
            ],
        ),
    ]
