# Generated by Django 2.0.2 on 2018-07-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0022_auto_20180629_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisannotation',
            name='analysis',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='linker.Analysis'),
            preserve_default=False,
        ),
    ]
