# Generated by Django 2.0.2 on 2018-07-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0024_auto_20180702_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisannotation',
            name='display_name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
