# Generated by Django 2.0 on 2018-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0027_auto_20180705_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissample',
            name='factor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
