# Generated by Django 2.0 on 2018-07-10 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0029_analysisdata_json_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='analysis_data',
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='display_name',
            field=models.CharField(default='Reactome mapping', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='inference_type',
            field=models.IntegerField(blank=True, choices=[(None, '-'), (0, 't-test'), (4, 'Hierarchical Clustering')], null=True),
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
