# Generated by Django 2.0 on 2018-07-10 10:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0030_auto_20180710_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='inference_params',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
