# Generated by Django 2.1.1 on 2018-10-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0034_auto_20180717_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdata',
            name='inference_type',
            field=models.IntegerField(blank=True, choices=[(None, '-'), (0, 't-test')], null=True),
        ),
    ]
