# Generated by Django 2.2 on 2019-04-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0037_analysisselection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalysisSelection',
            new_name='AnalysisGroup',
        ),
        migrations.RenameField(
            model_name='analysisgroup',
            old_name='selection_state',
            new_name='linker_state',
        ),
    ]
