# Generated by Django 2.2.13 on 2020-08-17 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0041_auto_20200817_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
