# Generated by Django 2.2.22 on 2021-06-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0044_auto_20210622_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
