# Generated by Django 2.2.22 on 2021-08-18 14:08

from django.db import migrations, models
import linker.models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0045_analysis_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisupload',
            name='mofa_data',
            field=models.FileField(blank=True, null=True, upload_to=linker.models.get_upload_folder),
        ),
    ]
