# Generated by Django 2.2.22 on 2021-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0046_analysisupload_mofa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisannotation',
            name='data_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='analysisdata',
            name='data_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='inference_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
