# Generated by Django 2.2.22 on 2021-09-26 12:10

from django.db import migrations, models
import linker.models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0046_analysisupload_mofa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisupload',
            name='metadata',
            field=models.FileField(blank=True, null=True, upload_to=linker.models.get_upload_folder),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='inference_type',
            field=models.IntegerField(blank=True, choices=[(None, '-'), (1, 'Differential Expression Analysis (t-test)'), (7, 'Differential Expression Analysis (DESeq2)'), (8, 'Differential Expression Analysis (limma)'), (3, 'Principal Component Analysis (PCA)'), (4, 'Pathway Analysis (PLAGE)'), (5, 'Pathway Analysis (ORA)'), (6, 'Pathway Analysis (GSEA)'), (9, 'Reactome Analysis Service'), (10, 'Multi-Omics Factor Analysis')], null=True),
        ),
    ]
