# Generated by Django 2.0.2 on 2018-06-12 10:58

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('species', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('genes_json', jsonfield.fields.JSONField()),
                ('proteins_json', jsonfield.fields.JSONField()),
                ('compounds_json', jsonfield.fields.JSONField()),
                ('reactions_json', jsonfield.fields.JSONField()),
                ('pathways_json', jsonfield.fields.JSONField()),
                ('gene_proteins_json', jsonfield.fields.JSONField()),
                ('protein_reactions_json', jsonfield.fields.JSONField()),
                ('compound_reactions_json', jsonfield.fields.JSONField()),
                ('reaction_pathways_json', jsonfield.fields.JSONField()),
            ],
        ),
    ]
