# Generated by Django 2.0.2 on 2018-06-14 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0004_auto_20180613_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', jsonfield.fields.JSONField()),
                ('data_type', models.IntegerField(choices=[(0, 'Genomics'), (1, 'Transcriptomics'), (2, 'Proteomics'), (3, 'Metabolomics')])),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.IntegerField(choices=[(0, 'Genomics'), (1, 'Transcriptomics'), (2, 'Proteomics'), (3, 'Metabolomics')])),
                ('inference_type', models.IntegerField(choices=[(0, 'Fold Change'), (1, 'Transcriptomics'), (2, 'Proteomics'), (3, 'Principal Component Analysis'), (4, 'Partial Least Square - Disciminant Analysis'), (5, 'Hierarchical Clustering'), (6, 'K-Means')])),
                ('params', jsonfield.fields.JSONField()),
                ('results', jsonfield.fields.JSONField()),
                ('timestamp', models.DateField(default=datetime.date.today)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('analysis_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.AnalysisData')),
            ],
        ),
    ]
