# Generated by Django 2.0.2 on 2018-06-14 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0007_auto_20180614_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='analysissample',
            name='label',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='linker.AnalysisData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysissample',
            name='group_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysissample',
            name='sample_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 17, 2, 34, 936887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 17, 2, 34, 938575, tzinfo=utc)),
        ),
    ]
