# Generated by Django 2.0.2 on 2018-06-14 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0008_auto_20180614_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 17, 3, 53, 134027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 17, 3, 53, 136281, tzinfo=utc)),
        ),
    ]
