# Generated by Django 2.0.2 on 2018-06-14 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0009_auto_20180614_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 17, 4, 29, 923082, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 17, 4, 29, 924753, tzinfo=utc)),
        ),
    ]
