# Generated by Django 2.0.2 on 2018-06-14 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0010_auto_20180614_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
