# Generated by Django 2.0.2 on 2018-06-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0017_auto_20180625_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisupload',
            name='species',
        ),
        migrations.AddField(
            model_name='analysisuploadspecies',
            name='analysis_upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='linker.AnalysisUpload'),
            preserve_default=False,
        ),
    ]
