# Generated by Django 2.0.2 on 2018-07-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0023_analysisannotation_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissample',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
