# Generated by Django 2.0.2 on 2018-07-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0025_analysisannotation_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='display_name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='inference_type',
            field=models.IntegerField(choices=[(None, '-'), (0, 't-test')]),
        ),
    ]
