# Generated by Django 2.0 on 2018-07-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0031_analysisdata_inference_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisdata',
            old_name='inference_params',
            new_name='metadata',
        ),
    ]
