# Generated by Django 2.0 on 2018-07-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0032_auto_20180710_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linker.AnalysisData'),
        ),
    ]
