# Generated by Django 2.0 on 2018-07-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0033_analysisdata_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissample',
            name='analysis_data',
        ),
        migrations.DeleteModel(
            name='AnalysisSample',
        ),
    ]
